nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

npmScopes:
  soda:
    npmPublishRegistry: https://npm.pkg.github.com
    npmAlwaysAuth: true
    npmAuthToken: ${NODE_AUTH_TOKEN}

yarnPath: .yarn/releases/yarn-3.6.0.cjs
