name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Enable Corepack
        run: corepack enable
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn test